---
development:
  cloud_name: hr0v6dg24
  api_key: "243252674515468"
  api_secret: rxaZrsPJmyR1GTvNlfV6g-uxn0k
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: hr0v6dg24
  api_key: "243252674515468"
  api_secret: rxaZrsPJmyR1GTvNlfV6g-uxn0k
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: hr0v6dg24
  api_key: "243252674515468"
  api_secret: rxaZrsPJmyR1GTvNlfV6g-uxn0k
  enhance_image_tag: true
  static_file_support: false
